name: Main workflow
on: push
jobs:
  build: 
    runs-on: ubuntu-22.04
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Build application
        run: ci/build-app.sh

      - name: Test application
        run: ci/unit-test-app.sh

      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
         name: code
         path: .
         include-hidden-files: true

  linting:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      
      - name: Run linting
        uses: super-linter/super-linter/slim@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
