name: Main workflow
on: push
env:
  docker_username: sirvingethesecond
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build: 
    runs-on: ubuntu-22.04
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build application
        run: ci/build-app.sh

      - name: Test application
        run: ci/unit-test-app.sh

      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
         name: code
         path: .
         include-hidden-files: true

  Linting:
    runs-on: ubuntu-22.04
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      
      - name: Run linting
        uses: super-linter/super-linter/slim@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

  Docker-image:
    runs-on: ubuntu-22.04
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4

      - name: Build Docker image
        run: bash ci/build-docker.sh

      - name: Push Docker image
        run: bash ci/push-docker.sh
        
