name: Main workflow
on: push
jobs:
  build: 
    runs-on: ubuntu-22.04
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - run: ci/build-app.sh
