name: Matrix workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        container: ["gradle:6-jdk8", "gradle:6-jdk11"]
    container:
      image: ${{ matrix.container }}   

    steps:
      - name: Clone repository
        uses: actions/checkout@v5      
      
      - name: Build application
        run: ci/build-app.sh
      
      - name: Test
        run: ci/unit-test-app.sh
